# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='None', max_length=20)),
                ('student_code', models.CharField(default='None', max_length=20)),
            ],
        ),
    ]
