# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEditor', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
