# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEditor', '0003_student_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='CourseEditor.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(default='0000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
