# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseEditor', '0004_auto_20170525_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
